apiVersion: v2
name: cloudflare-ddns
description: A Helm chart to deploy cloudflare DDNS on k8s

type: application

version: 0.1.3

# This is the version number ogf the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "latest"
